### ISSUE TITLE
Unable to write to EQ: Missing or unavailable event queue. err: Input/output error (5) 

### ISSUE THREAD

**Issue by yaroslavvb** [aws/aws-ofi-nccl#20] opened 2019-08-02 04:09 UTC
Running PyTorch through mpirun over EFA network I see the following error
[log](https://app.wandb.ai/yaroslavvb/imagenet18/runs/d80ov5h0/logs)
```
Unable to write to EQ: Missing or unavailable event queue. err: Input/output error (5) prov_errno: Unknown error -114 (-114) prov/rxr/src/rxr.h:1042 
```

This is connected to EFA since changing `FI_PROVIDER` to something besides `EFA` removes the error.

Also this error is related to PyTorch DataLoaders using fork strategy to create additional processes under mpirun. Changing strategy to `spawn` allows training to [proceed](https://app.wandb.ai/yaroslavvb/imagenet18/runs/v4b61xzj/logs) . Unfortunately there's a bug on the PyTorch side which limits number of GPUs that can be used with spawn

**Comment by rashikakheria** [comment] 2019-08-02 17:24
Thanks for reporting the issue. We have been able to reproduce the issue and we are continuing to investigate it. We will update this thread once we have a concrete understanding of the root cause.

**Comment by rashikakheria** [comment] 2019-08-08 19:59
The patch is open for review at https://github.com/ofiwg/libfabric/pull/5215. Please help us in testing it with your repro case.

**Comment by rajachan** [comment] 2019-08-16 07:15
The fix @rashikakheria references in the previous comment has been released with [AWS libfabric v1.8.0amzn1.1](https://github.com/aws/libfabric/releases/tag/v1.8.0amzn1.1). The latest version of the EFA installer also installs this version of AWS libfabric. Check out the [EFA documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-enable) for more information.

**Comment by rashikakheria** [comment] 2019-08-19 23:37
With this [patch](https://github.com/aws/aws-ofi-nccl/pull/21), the plugin can use the latest efa installer. Please use this commit if you want to test the latest efa installer.

**Comment by rashikakheria** [comment] 2019-09-11 21:39
Please re-open this issue if it still happens.

**Closed by rashikakheria** 2019-09-11 21:39 UTC
